name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make setup

      - name: Build
        run: make build

      - name: Run tests
        run: make test

      - name: Run lint
        run: make lint

      - name: Run format check (fail if formatting needed)
        run: |
          make format
          git diff --exit-code || (echo "Code not formatted, run make format locally" && exit 1)

